{-# LANGUAGE OverloadedStrings #-}

module Form where

import           Prelude
import           FormEngine.JQuery as JQ

import           FormEngine.FormItem
import           FormEngine.FormElement.FormElement as E
import           FormEngine.FormElement.Rendering
import           FormEngine.FormElement.Tabs
import           FormEngine.FormContext

generateForm :: [FormElement] -> IO ()
generateForm tabs = do
  formJq <- select "#form"
  let allTabs = aboutTab : tabs
  _ <- renderTabGroup allTabs (aboutTabPaneJq : tabsContentsJq tabs) formJq
  _ <- selectTab 0 allTabs
  fireClicks
  where
    tabsContentsJq :: [FormElement] -> [IO JQuery]
    tabsContentsJq = map makePaneJq
      where
        makePaneJq :: FormElement -> IO JQuery
        makePaneJq tab =
          select "<div class='main-pane'>"
          >>= inside
          >>= foldElements (E.children tab) (makeFormContext tabs) ElemBehaviour{ focusAction = noAction, blurAction = noAction } 
          >>= JQ.parent
    fireClicks :: IO ()
    fireClicks = do
      _ <- select "input:checked" >>= click >>= click
      _ <- select "input" >>= mouseleave
      _ <- select "textarea" >>= mouseleave
      _ <- select "select" >>= mouseleave
      return ()

aboutTab :: FormElement
aboutTab = ChapterElem
  { chfi = Chapter
    { chDescriptor = FIDescriptor
      { iLabel = Just "About"
      , iNumbering = Numbering [1000] 0
      , iIdent = Nothing
      , iTags = []
      , iShortDescription = Nothing
      , iLongDescription = Nothing
      , iLink = Nothing
      , iRules = []
      , iMandatory = False
      }
    , chItems = []
    }
  , chElements = []
  , visited = False
  }

aboutTabPaneJq :: IO JQuery
aboutTabPaneJq = select "\
\  <div>\
\    <p>\
\      This is a sample tabbed form generated by FormEngine.\
\    </p>\
\  </div>\
\ "

